version: "3.9"
services:
  postgres:
    container_name: PlantyApp_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "demoplants"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

